version: '3.8'

services:
  signbuddyapi:
    image: signbuddyapi
    secrets:
      - MONGO_URI_FULL
      - MONGO_URI_APPNAME
      - MONGO_DBNAME
      - AUTH0_DOMAIN
      - AUTH0_AUDIENCE
      - JWT_SIGN_KEY
      - LETTER_INFERENCE_URL
      - AUTH0_MANAGEMENT_ENDPOINT
      - ALLOWED_ORIGINS
      - AUTH0_MANAGEMENT_CLIENT_ID
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - AUTH0_MANAGEMENT_AUDIENCE
      - AUTH0_MANAGEMENT_GRANT_TYPE
      - AUTH0_MANAGEMENT_CURRENT_USER_ENDPOINT
      - AUTH0_SIGNBUDDY_MODEL_CLIENT_ID
      - AUTH0_SIGNBUDDY_MODEL_CLIENT_SECRET
      - AUTH0_SIGNBUDDY_MODEL_AUDIENCE
      - AUTH0_SIGNBUDDY_MODEL_GRANT_TYPE
      - JWT_APPLICATION_AUDIENCE
      - JWT_APPLICATION_ISSUER
      - JWT_APPLICATION_KEY
      - JWT_ALGORITHMS

secrets:
  MONGO_URI_FULL:
    file: ./secrets/MONGO_URI_FULL.txt
  MONGO_URI_APPNAME:
    file: ./secrets/MONGO_URI_APPNAME.txt
  MONGO_DBNAME:
    file: ./secrets/MONGO_DBNAME.txt
  AUTH0_DOMAIN:
    file: ./secrets/AUTH0_DOMAIN.txt
  AUTH0_AUDIENCE:
    file: ./secrets/AUTH0_AUDIENCE.txt
  JWT_SIGN_KEY:
    file: ./secrets/JWT_SIGN_KEY.txt
  LETTER_INFERENCE_URL:
    file: ./secrets/LETTER_INFERENCE_URL.txt
  AUTH0_MANAGEMENT_ENDPOINT:
    file: ./secrets/AUTH0_MANAGEMENT_ENDPOINT.txt
  ALLOWED_ORIGINS:
    file: ./secrets/ALLOWED_ORIGINS.txt
  AUTH0_MANAGEMENT_CLIENT_ID:
    file: ./secrets/AUTH0_MANAGEMENT_CLIENT_ID.txt
  AUTH0_MANAGEMENT_CLIENT_SECRET:
    file: ./secrets/AUTH0_MANAGEMENT_CLIENT_SECRET.txt
  AUTH0_MANAGEMENT_AUDIENCE:
    file: ./secrets/AUTH0_MANAGEMENT_AUDIENCE.txt
  AUTH0_MANAGEMENT_GRANT_TYPE:
    file: ./secrets/AUTH0_MANAGEMENT_GRANT_TYPE.txt
  AUTH0_MANAGEMENT_CURRENT_USER_ENDPOINT:
    file: ./secrets/AUTH0_MANAGEMENT_CURRENT_USER_ENDPOINT.txt
  AUTH0_SIGNBUDDY_MODEL_CLIENT_ID:
    file: ./secrets/AUTH0_SIGNBUDDY_MODEL_CLIENT_ID.txt
  AUTH0_SIGNBUDDY_MODEL_CLIENT_SECRET:
    file: ./secrets/AUTH0_SIGNBUDDY_MODEL_CLIENT_SECRET.txt
  AUTH0_SIGNBUDDY_MODEL_AUDIENCE:
    file: ./secrets/AUTH0_SIGNBUDDY_MODEL_AUDIENCE.txt
  AUTH0_SIGNBUDDY_MODEL_GRANT_TYPE:
    file: ./secrets/AUTH0_SIGNBUDDY_MODEL_GRANT_TYPE.txt
  JWT_APPLICATION_AUDIENCE:
    file: ./secrets/JWT_APPLICATION_AUDIENCE.txt
  JWT_APPLICATION_ISSUER:
    file: ./secrets/JWT_APPLICATION_ISSUER.txt
  JWT_APPLICATION_KEY:
    file: ./secrets/JWT_APPLICATION_KEY.txt
  JWT_ALGORITHMS:
    file: ./secrets/JWT_ALGORITHMS.txt